export default {
  login: "MastooraTurkmen",
  id: 132576850,
  node_id: "U_kgDOB-b2Ug",
  avatar_url: "https://avatars.githubusercontent.com/u/132576850?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/MastooraTurkmen",
  html_url: "https://github.com/MastooraTurkmen",
  followers_url: "https://api.github.com/users/MastooraTurkmen/followers",
  following_url: "https://api.github.com/users/MastooraTurkmen/following{/other_user}",
  gists_url: "https://api.github.com/users/MastooraTurkmen/gists{/gist_id}",
  starred_url: "https://api.github.com/users/MastooraTurkmen/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/MastooraTurkmen/subscriptions",
  organizations_url: "https://api.github.com/users/MastooraTurkmen/orgs",
  repos_url: "https://api.github.com/users/MastooraTurkmen/repos",
  events_url: "https://api.github.com/users/MastooraTurkmen/events{/privacy}",
  received_events_url: "https://api.github.com/users/MastooraTurkmen/received_events",
  type: "User",
  site_admin: false,
  name: "Mastoora Turkmen",
  company: null,
  blog: "https://mastooraturkmen.me/",
  location: "Kabul, Afghanistan",
  email: null,
  hireable: null,
  bio: "Let's code together and make an impact in the digital world! 😁❤️😍🤠",
  twitter_username: "MastooraJ22",
  public_repos: 110,
  public_gists: 0,
  followers: 92,
  following: 93,
  created_at: "2023-05-04T12:34:39Z",
  updated_at: "2024-03-15T12:00:08Z"
};
